import Link from "next/link";
import { PortalPage } from "@/components/portal/portal-page";

const modules = [
  { href: "/proveedor", role: "Proveedor", title: "Resumen", description: "Sesiones activas, cumplimiento y crédito" }, { href: "/proveedor/solicitudes", role: "Proveedor", title: "Solicitudes", description: "Crear, pagar y seguir transmisiones" }, { href: "/proveedor/credito", role: "Proveedor", title: "Crédito a favor", description: "Saldo, vencimientos y aplicaciones" }, { href: "/colaborador", role: "Colaborador", title: "Actividad", description: "Nivel, próxima sesión y saldo" }, { href: "/colaborador/turnos", role: "Colaborador", title: "Turnos disponibles", description: "Postulación y cupos" }, { href: "/colaborador/sesion", role: "Colaborador", title: "Sesión activa", description: "Heartbeat y cumplimiento" }, { href: "/colaborador/saldo", role: "Colaborador", title: "Saldo y retiros", description: "Disponible, revisión y solicitudes" }, { href: "/admin", role: "Admin", title: "Operaciones", description: "Alertas y sesiones activas" }, { href: "/admin/disputas", role: "Admin", title: "Disputas", description: "Evidencia y resoluciones" }, { href: "/admin/usuarios", role: "Admin", title: "Usuarios", description: "Búsqueda, estado y suspensión" }, { href: "/admin/retiros", role: "Admin", title: "Retiros", description: "Control de caja y lotes" }, { href: "/admin/configuracion", role: "Admin", title: "Reglas", description: "Parámetros de negocio" },
];

export function ModuleIndexPage() {
  return <PortalPage area="Panel" userName="Equipo de operaciones" initials="OP"><main className="mx-auto max-w-[1440px] px-5 py-8 lg:px-10 lg:py-10"><p className="eyebrow">MAPA DEL MVP</p><h1 className="font-display mt-1 text-3xl font-bold sm:text-4xl">Panel de módulos</h1><p className="mt-2 text-sm text-[#66716e]">Acceso a todas las áreas operativas de la plataforma.</p><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{modules.map((module) => <Link key={module.href} href={module.href} className="surface group p-5 transition hover:-translate-y-0.5 hover:border-[#9dbb86]"><p className="eyebrow">{module.role}</p><h2 className="font-display mt-2 text-xl font-bold group-hover:text-[#1f655d]">{module.title}</h2><p className="mt-2 text-sm leading-6 text-[#66716e]">{module.description}</p></Link>)}</section></main></PortalPage>;
}