import { Bell, CalendarDays, ChevronDown, CircleHelp, Clock3, CreditCard, Plus, ShieldCheck, UsersRound } from "lucide-react";
import type { ProviderDashboardData } from "@/lib/domain/types";
import { NewRequestForm } from "./new-request-form";

export function ProviderDashboard({ dashboard }: { dashboard: ProviderDashboardData }) {
  const { provider, metrics, activeSession, recentRequests } = dashboard;
  const progress = (activeSession.elapsedMinutes / activeSession.totalMinutes) * 100;

  return <div className="min-h-screen bg-[#f6f7f3] text-[#172129]">
    <header className="border-b border-[#dde2dc] bg-[#fbfcf9]"><div className="mx-auto flex h-[72px] max-w-[1440px] items-center justify-between px-5 lg:px-10"><div className="flex items-center gap-10"><a className="flex items-center gap-2.5" href="#top"><span className="grid h-8 w-8 place-items-center rounded-[7px] bg-[#d9f05b] text-sm font-black">V</span><span className="font-display text-xl font-bold">Vivo</span></a><nav className="hidden gap-1 md:flex"><a className="nav-link active" href="#top">Resumen</a><a className="nav-link" href="#history">Solicitudes</a></nav></div><div className="flex items-center gap-2"><button className="icon-button" aria-label="Ayuda" title="Ayuda"><CircleHelp size={19} /></button><button className="icon-button relative" aria-label="Notificaciones" title="Notificaciones"><Bell size={19} /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-[#f06449]" /></button><button className="ml-1 flex items-center gap-2 rounded-md py-1 pl-1 pr-2 text-sm font-semibold"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#1f655d] text-xs text-white">{provider.initials}</span><span className="hidden sm:block">{provider.businessName}</span><ChevronDown size={15} /></button></div></div></header>
    <main id="top" className="mx-auto max-w-[1440px] px-5 py-8 lg:px-10 lg:py-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">PANEL DE PROVEEDOR</p><h1 className="font-display mt-1 text-3xl font-bold sm:text-4xl">Buen día, {provider.businessName}</h1><p className="mt-2 text-sm text-[#66716e]">Coordiná participación real para tus transmisiones en vivo.</p></div><a href="#request" className="command-button"><Plus size={18} />Nueva solicitud</a></div>
      <section className="grid gap-4 lg:grid-cols-4"><Metric icon={<UsersRound size={19} />} title="Participantes activos" value={metrics.activeParticipants.toString()} detail={`en ${metrics.activeBroadcasts} transmisiones`} dark /><Metric icon={<ShieldCheck size={19} />} title="Cumplimiento promedio" value={`${metrics.averageCompliancePct}%`} detail="últimas 12 sesiones" /><Metric icon={<CalendarDays size={19} />} title="Próxima sesión" value={metrics.nextSession} detail={`${metrics.nextSessionParticipants} participantes`} /><Metric icon={<CreditCard size={19} />} title="Crédito disponible" value={`USD ${provider.availableCreditUsd.toFixed(2)}`} detail="Aplicable a una nueva solicitud" /></section>
      <section className="mt-7 grid gap-7 xl:grid-cols-[1.35fr_.85fr]"><div className="space-y-7"><article className="surface overflow-hidden"><div className="flex items-center justify-between border-b border-[#e3e7e1] px-5 py-4"><div><p className="eyebrow">EN CURSO</p><h2 className="font-display mt-1 text-xl font-bold">Transmisión de hoy</h2></div><span className="status-live"><i />En vivo</span></div><div className="grid gap-6 p-5 md:grid-cols-[1.35fr_.85fr]"><div><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-md bg-[#e5efe9] font-bold text-[#1f655d]">{provider.initials}</div><div><h3 className="font-bold">{activeSession.title}</h3><p className="text-sm text-[#66716e]">{activeSession.platform} · {activeSession.startTime} - {activeSession.endTime}</p></div></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-[#e7ebe5]"><div className="h-full rounded-full bg-[#75a744]" style={{ width: `${progress}%` }} /></div><div className="mt-2 flex justify-between text-xs text-[#6b7672]"><span>{activeSession.elapsedMinutes} min transcurridos</span><span>{activeSession.totalMinutes - activeSession.elapsedMinutes} min restantes</span></div></div><div className="border-[#e1e6dd] md:border-l md:pl-6"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#79837f]">Verificación humana</p><div className="mt-3 flex items-end gap-2"><strong className="font-display text-4xl">{activeSession.confirmedParticipants}/{activeSession.requiredParticipants}</strong><span className="mb-1.5 text-sm text-[#4e6f5d]">presencias confirmadas</span></div><p className="mt-3 text-sm leading-6 text-[#66716e]">Último check-in hace {activeSession.lastHeartbeatMinutesAgo} min. Próximo control a las {activeSession.nextHeartbeatAt}.</p></div></div><div className="flex items-center gap-2 border-t border-[#e3e7e1] bg-[#fafbf8] px-5 py-3 text-sm text-[#52605a]"><Clock3 size={16} />Seguimiento en tiempo real</div></article>
      <article id="history" className="surface"><div className="px-5 pb-3 pt-5"><p className="eyebrow">HISTORIAL RECIENTE</p><h2 className="font-display mt-1 text-xl font-bold">Solicitudes</h2></div><div className="overflow-x-auto"><table><thead><tr><th>Sesión</th><th>Fecha</th><th>Participación</th><th>Estado</th></tr></thead><tbody>{recentRequests.map((request) => <tr key={request.id}><td><strong>{request.title}</strong><span>{request.platform} · {request.participants} participantes</span></td><td>{request.scheduledAt}</td><td><b>{request.compliancePct}%</b><div className="tiny-bar"><i style={{ width: `${request.compliancePct}%` }} /></div></td><td><span className={request.status === "completed" ? "status good" : "status review"}>{request.status === "completed" ? "Completada" : "Crédito emitido"}</span></td></tr>)}</tbody></table></div></article></div><NewRequestForm availableCreditUsd={provider.availableCreditUsd} /></section>
    </main>
  </div>;
}

function Metric({ icon, title, value, detail, dark = false }: { icon: React.ReactNode; title: string; value: string; detail: string; dark?: boolean }) { return <article className={`metric-card ${dark ? "dark-card" : ""}`}><div className="metric-icon">{icon}</div><p>{title}</p><strong>{value}</strong><span>{detail}</span></article>; }